name: Deploy Sphinx Docs to S3 and GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Install Python 3.12
        run: uv python install 3.12

      - name: Build Sphinx HTML
        run: uv run make html

      - name: Upload artifact (for S3)
        uses: actions/upload-artifact@v4
        with:
          name: sphinx-docs
          path: build/html

      - name: Upload artifact (for GitHub Pages)
        uses: actions/upload-pages-artifact@v3
        with:
          path: build/html

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deploy-pages.outputs.page_url }}

    steps:
      - name: Download artifact (for S3)
        uses: actions/download-artifact@v4
        with:
          name: sphinx-docs
          path: build/html

      - name: Deploy to GitHub Pages
        id: deploy-pages
        uses: actions/deploy-pages@v4